Translation for Main Concepts' Handling Events page.
reactjs/ur.reactjs.org pull request #23
Opened 2020-07-31 14:19 UTC by asheerrizvi

Please point out any grammatical or spelling correction(s) which needs to be made and I'll fix it. Would also appreciate suggestions on words which could be further translated or presented in a better way. 

#22

2020-08-03 10:01 UTC, jabranr commented on content/docs/handling-events.md
> +* JSX میں آپ فنکشن پاس کریں گے بتور ایونٹ ہینڈلر بجائے ایک string کے
```suggestion
* JSX میں آپ فنکشن پاس کریں گے بطور ایونٹ ہینڈلر بجائے ایک string کے
```

2020-08-03 10:02 UTC, jabranr commented on content/docs/handling-events.md
> +* JSX میں آپ فنکشن پاس کریں گے بتور ایونٹ ہینڈلر بجائے ایک string کے
Keep order in sentences

```suggestion
* JSX میں آپ event handler کو string کی بجائے function کے طور پر پیش کرتے ہیں
```

2020-08-03 10:07 UTC, jabranr commented on content/docs/handling-events.md
> +یہاں پہ `e` ایک synthethic ایونٹ ہے، ان synthetic ایونٹس کو React نے [W3C spec](https://www.w3.org/TR/DOM-Level-3-Events/) کو مدنظر رکھتے ہوئے بنایا ہے  لہٰذا یہ کراس-براوزر مطابقت رکھتے ہیں ۔ اس موض
```suggestion
یہاں پہ `e` ایک synthethic ایونٹ ہے، ان synthetic ایونٹس کو React نے [W3C spec](https://www.w3.org/TR/DOM-Level-3-Events/) کو مدنظر رکھتے ہوئے بنایا ہے  لہٰذا یہ مختلف براوزر مطابقت رکھتے ہیں ۔ اس موضوع پہ مزید معلومات حاصل کرنے کے لیے [`SyntheticEvent`](/docs/events.html) سے منسوب گائیڈ کو ملاحظہ فرمائیں
```

2020-08-03 10:12 UTC, jabranr commented on content/docs/handling-events.md
> +جب آپ [ES6 class](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Classes) کا استعمال کرتے ہوئے جزو بناتے ہیں تو ایک آم پیٹرن یہ ہے کہ ایونٹ ہینڈلر کو اس class کا طریقہ یا method بنا د
```suggestion
جب آپ [ES6 class](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Classes) کا استعمال کرتے ہوئے جزو بناتے ہیں تو ایک عام طریقہ کار یہ ہے کہ ایونٹ ہینڈلر کو اس class کا طریقہ یا method بنا دیا جائے ۔ مثال کے طور پہ یہ `Toggle` جزو ایک بٹن render کر رہا ہے جس سے ایک صارف "ON" اور "OFF" states کے درمیان ٹوگل کر سکتا ہے
```

2020-08-03 11:22 UTC, asheerrizvi commented
> There are way too many changes required. This is not a good translation. There are typos, incorrect sentences. I have given some suggestions but I don't want to go through rest of the it unless you go through it first and re-think the translation.

@jabranr Thank you for the feedback, I was unsure about many things so I wanted to put something out first. I will improve on your suggestions and come up with something better.

2020-09-21 10:07 UTC, jabranr requested changes
Great work! Thank you. Just couple of changes for typos.

2020-09-21 10:07 UTC, jabranr commented on content/docs/handling-events.md
> +Loop کے اندر event handler میں ایک اضافی parameter فراہم کرنا ایک آم عمل ہے، مثلاً اگر `id` کو  row ID سے نسبت دی جائے تو ان میں سے کوئی بھی طریقہ استعمال میں لایا جا سکتا ہے
```git
- آم
+ عام
```

2020-09-21 10:07 UTC, jabranr commented on content/docs/handling-events.md
> +جب آپ [ES6 class](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Classes) کا استعمال کرتے ہوئے جزو بناتے ہیں تو ایک آم طریقہ کار یہ ہے کہ event handler کو اس class کا طریقہ (method) ب
```
- آم
+ عام
```

2020-09-27 12:19 UTC, asheerrizvi commented
@jabranr thanks! I have done the requested changes, you can check now.

2020-09-28 13:16 UTC, jabranr approved these changes

2020-09-28 13:18 UTC, merged